Repository DeveloperAcademy-POSTECH/MC3-Team-12-Makers, pull requests merged in 2022-07, with the labels that each got.

#6 [ADD] ParentUser Data, TeacherUser Data 모델 추가
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
  Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
  Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift
Labels: 🥝 Youth, ⚪️ Logic

#9 [ADD] MockData추가
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
  Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift
Labels: 🥝 Miller, 🥝 Youth, 🧬 Model

#10 [ADD] 캘린더뷰1차
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Base/BaseCollectionViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/CalenderViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/TestG.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
Labels: 🥝 Rev

#11 [FEAT] 학부모 쪽지건의 화면
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
Labels: 🥝 Hero, 🏞 UI

#16 [ADD] 캘린더뷰 탭 분리 및 PR반영
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
Labels: 🥝 Rev, 🏞 UI

#20 [ADD] 교사 쪽지건의 탭 구현(Data Struct 구조 변경 및 MockData에 긴급메세지 추가)
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/ReceivingViewController.swift
Labels: 🥝 Youth, 🏞 UI, ⚪️ Logic, 🧬 Model

#27 [ADD] 알림창구현(긴급알림, 일반알림(쪽지, 상담신청)) - 임시코드
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Youth, 🏞 UI

#18 [ADD] 학부모 캘린더뷰 데이터 연결
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🥝 Rev, 🧬 Model

#21 [ADD] 학부모 쪽지건의 화면 업데이트 (기전송 리스트, 새로운 쪽지 발송 버튼 연결)
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
Labels: 🥝 Hero, 🏞 UI

#25 [ADD] 교사 캘린더뷰 일부 구현 - 학부모별/전체 상담예약 표시
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/TestJ.swift
  Gajeongtongsin/Gajeongtongsin/Models/teacherCalenderData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🥝 Rev, 🏞 UI, 🧬 Model

#26 [ADD] 학부모 전화상담 뷰 (일반상담예약 뷰, 기능 미구현)
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
Labels: 🥝 Hero, 🏞 UI

#31 [FIX] 파일 컨플릭트 수정
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Labels: 🐞Bug

#32 [CHORE] Notification struct고려한 mock data 수정 및 알림창과 메세지뷰 로직 재구현
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Youth, 🏞 UI, 🧬 Model

#36 [FIX] MessageType .emergency삭제
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift
Labels: 🥝 Youth, 🧬 Model

#37 [ADD] 학부모 전화예약 리스트 테이블뷰
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
  Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
Labels: 🥝 Hero, 🏞 UI, ⚪️ Logic

#38 [ADD] 교사 캘린더뷰 예약확정 기능 및 확정 팬딩 구현
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
  Gajeongtongsin/Gajeongtongsin/Models/teacherCalenderData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🥝 Rev, 🏞 UI, ⚪️ Logic

#45 [ADD] 교사 캘린더뷰 - 학부모 목록 버튼에서 테이블뷰로 변경
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/Cell/CalenderTabelViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/Cell/TestB.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🥝 Rev, 🏞 UI

#46 [FIX] Data구조변경
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
  Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
Labels: 🥝 Youth, 🧬 Model

#47 [FEAT] 파이어베이스 세팅 및 업로드 함수 구현
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
  Gajeongtongsin/Gajeongtongsin/Global/Supports/AppDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Global/Supports/SceneDelegate.swift
  Gajeongtongsin/Gajeongtongsin/GoogleService-Info.plist
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
  Gajeongtongsin/Gajeongtongsin/Models/ParentUser.swift
  Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
  Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Login/StartViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
Labels: 🥝 Miller, 📒 Firebase

#48 [ADD] CustomNavigationBar & AlertView 화면전환구현
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Extension/UIColor+Extension.swift
  Gajeongtongsin/Gajeongtongsin/Global/Protocol/CutomNavigationBarDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CutomNavigationBar.swift
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Youth, 🏞 UI

#55 [FIX] 7월28일 버그 #54 해결
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🐞Bug, 🥝 Youth

#57 [ADD] 메세지 보낸날짜를 section별로 분리해서 Teacher MessageView로 띄우기
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Extension/Date+Extension.swift
  Gajeongtongsin/Gajeongtongsin/Global/Extension/String+Extension.swift
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
Labels: 🥝 Youth, ⚪️ Logic, 🧬 Model

#53 [FEAT] firebase 가져오기 함수 구현
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
Labels: 🥝 Miller, 📒 Firebase

#63 [FIX] 컬러익스텐션오류 수정
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🐞Bug, 🥝 Youth

#64 [CHORE] Color extension으로 수정
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
Labels: 🐞Bug, 🥝 Youth

#51 [ADD] 학부모 전화상담 내역 상세 뷰 추가
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
Labels: 🥝 Hero, 🏞 UI, ⚪️ Logic

#61 [ADD] NotificationView Custom Section Bar 구현
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Extension/UIColor+Extension.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/CustomSectionBar.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Youth, 🏞 UI

#67 [FIX] 컬러익스텐션과 주의부분 수정
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
Labels: 🐞Bug, 🥝 Youth

#62 UI 컴포넌트 생성
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CardCollectionViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/PrimaryButton.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/SecondaryButton.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Monica, 🏞 UI

#66 [ADD] 학부모 회원가입창 구현
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Global/Supports/SceneDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Login/LabelFieldView.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Login/ParentRegistrationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Login/StartViewController.swift
Labels: 🥝 Miller, 🏞 UI, ⚪️ Logic
