Repository DeveloperAcademy-POSTECH/MC3-Team-12-Makers, pull requests merged in 2022-08, with the labels that each got.

#71 [FEAT] 파이어베이스 알림 연결
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
  Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Miller, 📒 Firebase

#76 [FIX] 부모 회원가입창 글자수 제한 오류 해결
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Screens/Login/ParentRegistrationViewController.swift
Labels: 🐞Bug, 🥝 Miller

#73 [CHORE] 학부모 뷰 세부 UI 조정
  Gajeongtongsin/Gajeongtongsin/Global/Extension/Date+Extension.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/PrimaryButton.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/SecondaryButton.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🐞Bug, 🥝 Hero, 🏞 UI

#81 [ADD] 전화예약 인디케이터 버튼 구현
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/SecondaryButton.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Hero, 🏞 UI, ⚪️ Logic

#75 [FEAT] 파이어베이스 메시지 연결
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/ReceivingViewController.swift
Labels: 🥝 Miller, 📒 Firebase

#80 [CHORE] TeacherView Navigation연결
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CutomNavigationBar.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
Labels: 🥝 Youth, 🏞 UI

#82 [CHORE] navigation bug fix
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
Labels: 🐞Bug, 🥝 Youth

#77 [ADD]교사 캘린더뷰에 학부모 컬렉션뷰 제작 및 HiFi 구현, 버그 다수 수정
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Global/Protocol/ParentsCollcetionViewCellDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CardCollectionViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/CalenderViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/Cell/CalenderTabelViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/Cell/ParentsCollectionViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Rev, 🏞 UI

#83 [FEAT] 파이어베이스 전화상담 연결
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Global/Protocol/ParentsCollcetionViewCellDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
  Gajeongtongsin/Gajeongtongsin/Global/Supports/Info.plist
  Gajeongtongsin/Gajeongtongsin/Global/Supports/SceneDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CardCollectionViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CustomNavigationBar.swift
  Gajeongtongsin/Gajeongtongsin/Models/Schedule.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/Cell/ParentsCollectionViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/NotificationTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Miller, 📒 Firebase

#87 [ADD] 학부모 전화예약뷰 HiFi / 예약불가셀 팬딩 추가(with MockData)
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/CalenderViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🥝 Rev, 🏞 UI, ⚪️ Logic

#88 [FIX] 테스트플라이트 데이터로 인한 튕김 오류 해결
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🐞Bug, 🥝 Rev

#84 [CHORE] CustomNavigationBar 일괄 수정, Secondary Button으로 상태 체크 인디케이터 적용
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CustomNavigationBar.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/Cell/SentMessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🥝 Hero, 🏞 UI

#86 [CHORE] 전체적인 디자인 수정 등 for 선생님
  Gajeongtongsin/Gajeongtongsin/Global/Literal/MockData.swift
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Gajeongtongsin/Gajeongtongsin/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
  Gajeongtongsin/Gajeongtongsin/Global/UIComponent/CustomNavigationBar.swift
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
Labels: 🥝 Miller, 📒 Firebase, 🏞 UI

#90 [FIX] customNavBar 에러 해결
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
Labels: 🐞Bug, 🥝 Miller

#94 [FEAT] 학부모 캘린더 pending 파이어베이스 연결
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
Labels: 🥝 Miller, 📒 Firebase

#93 [ADD] 학부모 전화상담 신청 시 textview 수정
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
Labels: 🐞Bug, 🥝 Hero, 🏞 UI

#91 [FIX]교사 캘린더뷰의 학부모 컬렉션뷰 예약확정시 밀림 버그 해결
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🐞Bug, 🥝 Rev

#96 [FIX]] backgroundcolor 수정
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SentMessageListViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/Cell/MessageTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/NotificationViewController.swift
Labels: 🥝 Miller, 🏞 UI

#105 [FIX] 데이터구조 수정
  Gajeongtongsin/Gajeongtongsin/Models/Message.swift
  Gajeongtongsin/Gajeongtongsin/Models/Notification.swift
  Gajeongtongsin/Gajeongtongsin/Models/ScheduleInfo.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherUser.swift
Labels: 🥝 Miller, 🥝 Youth, 🧬 Model

#99 [FIX] 확정하기시 크래쉬 해결 및 캘린더쪽 코드리팩토링
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Login/ParentRegistrationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/Cell/ScheduleTableViewCell.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationDetailViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🐞Bug, 🥝 Miller, 🛠 Refactoring
