Repository DeveloperAcademy-POSTECH/MC3-Team-12-Makers, pull requests merged in 2022-09, with the labels that each got.

#112 [FEAT] 토스트메시지 구현 완료
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ReservationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Sending/SendingViewController.swift
Labels: 🥝 Hero, 🏞 UI

#113 [FEAT] 키보드 높이 조절 구현
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
Labels: 🐞Bug, 🥝 Hero, 🏞 UI

#115 [ADD] 교사 한정 슬롯 추가/삭제 구현 완료 (목데이터로 구동)
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/CalenderSlotMockData.swift
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Models/CalenderSlotData.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Receiving/MessageVIewController.swift
Labels: 🥝 Rev, 🏞 UI, ⚪️ Logic

#116 [FEAT] 긴급알림 PushNotification 구현
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Gajeongtongsin.entitlements
  Gajeongtongsin/Gajeongtongsin/Global/Base/BaseViewController.swift
  Gajeongtongsin/Gajeongtongsin/Global/Service/FirebaseManager.swift
  Gajeongtongsin/Gajeongtongsin/Global/Service/PushNotificationManager.swift
  Gajeongtongsin/Gajeongtongsin/Global/Supports/AppDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Global/Supports/Info.plist
  Gajeongtongsin/Gajeongtongsin/Screens/Login/ParentRegistrationViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Login/StartViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/UrgentRequestViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
Labels: 🥝 Miller, 📒 Firebase, ⚪️ Logic

#117 [FEAT] 학부모 슬롯 연동 / 캘린더 이번, 다음주 구현
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Global/CalenderSlotMockData.swift
  Gajeongtongsin/Gajeongtongsin/Global/Literal/Constants.swift
  Gajeongtongsin/Gajeongtongsin/Global/Protocol/DateLabelViewDelegate.swift
  Gajeongtongsin/Gajeongtongsin/Models/TeacherCalenderData.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Parent/Reservation/ParentsCalenderViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Teacher/Consultation/ConsultationViewController.swift
Labels: 🥝 Rev, ⚪️ Logic

#119 [ADD] parent profile view
  Gajeongtongsin/Gajeongtongsin.xcodeproj/project.pbxproj
  Gajeongtongsin/Gajeongtongsin/Screens/Profile/ParentProfileViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/Profile/ProfileViewController.swift
  Gajeongtongsin/Gajeongtongsin/Screens/TabBar/TabBarViewController.swift
Labels: 🥝 Miller, 🏞 UI
